"""Create a program that will play the cows and bulls game with the user. The game works like this:
Randomly generate a 4-digit number. Ask the user to guess a 4-digit number. 
For every digit that the user guessed correctly in the correct place, 
they have a cow. For every digit the user guessed correctly in the wrong place is a bull.
Every time the user makes a guess, tell them how many cows and bulls they have.
 Once the user guesses the correct number, the game is over. 
 Keep track of the number of guesses the user makes throughout the game and tell the user at the end.
Say the number generated by the computer is 1038. An example interaction could look like this:
  Welcome to the Cows and Bulls Game! 
  Enter a number: 
  >>> 1234
  2 cows, 0 bulls
  >>> 1256
  1 cow, 1 bull"""
from random import randint
print "Welcome to cows and bulls game"
y=True
counter=0  


randomnum=randint(1000,9999)
print "random number is:",randomnum
while(y):
    a=str(randomnum)
    b=[ ]
    for i in a:
        b.append(int(i))
    user=input("enter any four digit number")
    c=str(user)
    d=[ ]
    for j in c:
        d.append(int(j))
    cows=0
    bulls=0 
        
    for k in range(len(b)):
            if b[k]==d[k]: 
                cows+=1
            else:
                bulls+=1
    counter+=1
    print "cows and bulls are",(cows,bulls)
    print "guesses are",counter
    y=input("Do u want to play other game?? press True or False:")
                    
                      
